---
title: "viz_and_eda"
author: "Carolina Montes Garcia"
date: "2024-09-26"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = case_match(
      id, 
      "USW00094728" ~ "CentralPark_NY", 
      "USW00022534" ~ "Molokai_HI",
      "USS0023B17S" ~ "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

Making our first plot :)

```{r}

ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()

```

```{r}
ggp_weather_scatterplot = 
  weather_df %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggp_weather_scatterplot
  
```

Fancier scatterplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .5) +
  geom_smooth(se = FALSE)
```


```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

LEt's make a somewhat more interesting scatterplot

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

```{r eval = FALSE}

colnames(weather_df)

weather_df = 
  filter(name == "CentralPark_NY") %>%  
  mutate(
    tmax_fahr = tmax * (9/5) + 32, 
    tmin_fahr = tmin * (9/5) + 32
  ) %>% 
  ggplot(aes(x = tmin_fahr, y = tmax_fahr)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE)
```

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth(se = FALSE) 
```


```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```

```{r}
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")
```

##Univariate plits

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, fill = name)) + 
  geom_histogram(position = "dodge")
```

how would I fix this? maybe facet?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, fill = name)) + 
  geom_histogram() +
  facet_grid(.~ name)
```

maybe a density plot?

```{r}
weather_df %>% 
  ggplot(aes(x = tmin, fill = name)) +
  geom_density(alpha = .3)
```

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmin, fill = name))+
  geom_boxplot()
```

violin plots
```{r}
weather_df %>% 
  ggplot(aes(x = name , y = tmin, fill = name)) +
  geom_violin()
```

```{r}
weather_df %>% 
  ggplot(aes(x = name , y = tmin)) +
  geom_density_ridges()
```

LEarning assessment
```{r}
weather_df %>% 
  ggplot(aes(x = name , y = prcp, fill = name)) +
  geom_violin()

weather_df %>% 
  ggplot(aes(x = name, y = prcp, fill = name))+
  geom_boxplot()

weather_df %>% 
  filter(prcp > 10, prcp < 1000) %>% 
  ggplot(aes(x = name, y = prcp, fill = name))+
  geom_boxplot()

weather_df %>% 
  filter(prcp > 10, prcp < 1000) %>% 
  ggplot(aes(x = prcp, fill = name))+
  geom_density(alpha = .3)
```

